#!/usr/bin/env php

<?php

use Rxak\App\App;
use Rxak\App\Console\Kernel;
use Rxak\Framework\Filesystem\Filesystem;

require __DIR__ . '/vendor/autoload.php';

Filesystem::init(__DIR__);

App::init();

$kernel = new Kernel();

$kernel->run();
